### PR TITLE
Add integration tests, fixes #63

### LINKED ISSUE #63: Add credentials to travis so that we can run the tests

### PR DESCRIPTION
**Pull request by germanattanasio**
Hey @dgterry I spent some time doing some cleanup and adding some tests to the app.

 * Added `casperjs` to do integration tests. We have 1 test that sends a message and expect a response from Conversation.
 * Cleanup the README. Now that we push the `.env` file to Bluemix users don't need to update the `WORKSPACE_ID` in the `manifest.yml` file.
 * Updated the `eslint` rules to match the code style of other es5 projects. 
 * Removed `console.error(err)` statements. If you want to log those errors we should think on using the `debug` module.

Please let me know if you have questions.

### CODE REVIEW

**Comment by dgterry** [comment]
@germanattanasio changes look reasonable to me and I'm inclined to merge it but I noticed one of the travis checks was still failing. Looks like one of the tests is still having trouble specifying workspace credentials?

**Comment by germanattanasio** [comment]
Yeah, it's better if you let me do more tests before merging it.

**Comment by dgterry** [comment]
@germanattanasio any chance you might be able to look at the tests again in the near future? Few PRs behind this and it would be good to know if the build is clean before merging those.  Thanks for any thoughts!

**Comment by germanattanasio** [comment]
Agree. Let me finish this today.

**Comment by germanattanasio** [comment]
This PR includes #69

**Comment by germanattanasio** [comment]
@dgterry, In order to enable blue-green deployments I had to change the service name from `conversion-service-DO-NOT-DELETE` to `my-conversation-service`. If you do manual deployments your manifest needs to be updated.

**Comment by germanattanasio** [comment]
This also closes #61

**Pull request merged**
